apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: egor-volkov-ikbo2421
spec:
  containers:
    - name: cpu-demo-ctr
      image: polinux/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      command: ["stress"]
      args:
        - "--cpu"
        - "2"
