apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: egor-volkov-ikbo2421
spec:
  containers:
    - name: cpu-demo-ctr-2
      image: polinux/stress
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
      command: ["stress"]
      args:
        - "--cpu"
        - "2"
