version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: 4WZsVGDrasDK
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  django:
    image: django:latest
    container_name: django
    build:
      context: MIREA_TVKSP_backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=adminuser
      - POSTGRES_PASSWORD=4WZsVGDrasDK
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my-network

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    networks:
      - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - my-network

  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    networks:
      - my-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: 4WZsVGDrasDK
      ZBX_JAVAGATEWAY_ENABLE: "false"
    depends_on:
      - postgres
    ports:
      - "10051:10051"
    networks:
      - my-network

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-5.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my-network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: