FROM openjdk:17-jdk-alpine AS builder
LABEL author="Volkov Egor Alexandrovich"
LABEL author_group="IKBO-24-21"
WORKDIR /app
COPY build.gradle settings.gradle /app/
COPY gradle /app/gradle
ENV GRADLE_HOME=/usr/local/gradle
ENV PATH=$PATH:$GRADLE_HOME/bin
COPY . .
RUN apk add --no-cache wget
RUN wget -O /app/src/main/resources/static/gerb.png https://www.mirea.ru/upload/medialibrary/80f/MIREA_Gerb_Colour.png
RUN ./gradlew build --no-daemon || return 0
RUN chmod +x ./gradlew
RUN ./gradlew build --no-daemon
RUN apk add --no-cache tree
CMD ls /app/src/main/resources/static/ && echo "Сборка завершена"


FROM openjdk:17-jdk-alpine
ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    APP_HOME=/usr/app/ \
    DB_PORT=5432
WORKDIR $APP_HOME
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
VOLUME /tmp
ENTRYPOINT ["java", "-jar", "app.jar"]
ONBUILD RUN echo "Сборка и запуск произведены. Автор: Волков Егор Александрович"