CREATE DATABASE test_db;
CREATE USER test_user WITH ENCRYPTED PASSWORD '4WZsVGDrasDK' NOCREATEDB NOCREATEROLE;
REVOKE ALL ON DATABASE test_db FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;
