apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fileserver
  name: fileserver
  namespace: default
spec:
    replicas: 2
    selector:
      matchLabels:
        app: fileserver
    template:
      metadata:
        labels:
          app: fileserver
      spec:
        containers:
        - image: fileserver:v1-abcde
          imagePullPolicy: Never
          name: fileserver
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            requests:
              cpu: "0.25"
              memory: "1G"
            limits:
              cpu: "0.25"
              memory: "1G"
        dnsPolicy: ClusterFirst
        restartPolicy: Always